[virtualenvs]
in-project = true

[tool.poetry]
name = "graph-llm-agents"
version = "0.1.0"
description = "A hub for exploring the integration of graph-based orchestration with LLMs, focusing on the development and experimentation of multi-actor LLM applications."
authors = ["Martin Fabbri <martin.fabbri.a@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = {extras = ["email"], version = "^1.10.8"}
langchain = "^0.1.10"
langchain-community = "^0.0.25"
langgraph = "^0.0.26"
langchainhub = "^0.1.14"


[tool.poetry.group.dev.dependencies]
black = "^24.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
